---
- name: install OMNeT++ dependencies
  package:
      name: "{{ packages }}"
      state: present
  vars:
      packages:
          - build-essential
          - gcc
          - g++
          - bison
          - flex
          - perl
          - python3
          - qt5-default
          - libosgearth-dev
          - libqt5opengl5-dev
          - libxml2-dev
          - zlib1g-dev
          - default-jre
  become: yes

- name: create /opt/omnetpp directory
  file:
      path: /opt/omnetpp
      state: directory
      owner: "{{ ansible_user }}"
  become: yes

- name: download OMNeT++ archive
  get_url:
      url: "{{ omnetpp_url }}/{{ omnetpp_archive }}"
      dest: /var/tmp/{{ omnetpp_archive }}
      checksum: "{{ omnetpp_checksum }}"

- name: extract OMNeT++ archive
  unarchive:
      src: /var/tmp/{{ omnetpp_archive }}
      dest: /opt/omnetpp/
      creates: /opt/omnetpp/configure
      extra_opts:
          - --strip-components=1

- name: configure OMNeT++
  command: ./configure
  args:
      chdir: /opt/omnetpp
      creates: /opt/omnetpp/Makefile.inc

- name: build OMNeT++
  make:
      chdir: /opt/omnetpp
      params: --jobs={{ ansible_processor_vcpus }}
  environment:
      PATH: /opt/omnetpp/bin:{{ ansible_env.PATH }}
  register: build_omnetpp
  changed_when: build_omnetpp.stdout is search('Creating')

- name: add OMNeT++ binary path to PATH
  copy:
      content: export PATH=/opt/omnetpp/bin:$PATH
      dest: /etc/profile.d/omnetpp.sh
  become: yes
